#!/bin/bash

CSURI=https://api.cloudsigma.com/
CSAUTH=renich@r-tech.com.mx:w4chuw4dru

usage() {
  cat >&2 <<EOF
Usage: $0 [ -c | -f FILENAME ] CMD [ARG]...
Options:
  -c            read input data for API call from stdin
  -f FILENAME   read input data for API call from FILENAME
  -v            show full headers sent and received during API call
EOF
  exit 1
}


if ! type -t curl >/dev/null; then
  echo "This tool requires curl, available from http://curl.haxx.se/" >&2
elif [ ! -n "$CSAUTH" ]; then
  echo "Please set CSAUTH=<username>:<password>" >&2
  exit 1
fi

DATA=""
TYPE=""
VERBOSE=""

while getopts cf:jv OPTION; do
  case "$OPTION" in
    c)
      DATA="-"
      ;;
    f)
      if [ -e "$OPTARG" ]; then
        case "$OPTARG" in
          /*)
            DATA="$OPTARG"
            ;;
          *)
            DATA="$PWD/$OPTARG"
            ;;
        esac
      else
        echo "$OPTARG not found" >&2
        exit 1
      fi
      ;;
    v)
      VERBOSE=-v
      ;;
    *)
      usage
      ;;
  esac
done
shift $(($OPTIND - 1))
[ $# -gt 0 ] || usage

CSURI="$CSURI`tr \  / <<< "$*"`"
CSAUTH="user = \"$CSAUTH\""

if [ -z "$DATA" ]; then
  curl --data-binary '' -K <(echo "$CSAUTH") -s $VERBOSE \
       ${TYPE:+-H "Accept: $TYPE"} "$CSURI"
else
  cat "$DATA" | curl --data-binary @- -K <(echo "$CSAUTH") -s $VERBOSE \
                     -H "Content-Type: ${TYPE:-application/octet-stream}" \
                     ${TYPE:+-H "Accept: $TYPE"} -H 'Expect:' "$CSURI"
fi
